// Auto-generated fallback dataset (used when the Flask backend is offline).
window.UNIVERSITY_DATA = [
  {
    "name": "FAST NUCES",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "CS, AI, SE, DS",
    "min_merit": 75,
    "max_merit": 95,
    "fee_per_year": 180000,
    "hostel": "Yes",
    "hec_rank": 1,
    "website": "nu.edu.pk",
    "deadline": "2026-08-15"
  },
  {
    "name": "NED University",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "Engineering, CS, Architecture",
    "min_merit": 70,
    "max_merit": 92,
    "fee_per_year": 45000,
    "hostel": "Yes",
    "hec_rank": 4,
    "website": "neduet.edu.pk",
    "deadline": "2026-07-30"
  },
  {
    "name": "IBA Karachi",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "Business, CS, Economics",
    "min_merit": 72,
    "max_merit": 93,
    "fee_per_year": 250000,
    "hostel": "Yes",
    "hec_rank": 6,
    "website": "iba.edu.pk",
    "deadline": "2026-07-20"
  },
  {
    "name": "Aga Khan University",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "Medicine, Nursing, Education",
    "min_merit": 85,
    "max_merit": 98,
    "fee_per_year": 500000,
    "hostel": "Yes",
    "hec_rank": 6,
    "website": "aku.edu.pk",
    "deadline": "2026-07-15"
  },
  {
    "name": "University of Karachi",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "Arts, Science, Commerce, Law, Pharmacy",
    "min_merit": 55,
    "max_merit": 82,
    "fee_per_year": 15000,
    "hostel": "Yes",
    "hec_rank": 9,
    "website": "uok.edu.pk",
    "deadline": "2026-09-10"
  },
  {
    "name": "Bahria University",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "CS, Engineering, Business",
    "min_merit": 62,
    "max_merit": 86,
    "fee_per_year": 140000,
    "hostel": "Yes",
    "hec_rank": 10,
    "website": "bahria.edu.pk",
    "deadline": "2026-08-30"
  },
  {
    "name": "SZABIST",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "CS, Business, Media Sciences, Engineering",
    "min_merit": 65,
    "max_merit": 88,
    "fee_per_year": 180000,
    "hostel": "Yes",
    "hec_rank": 13,
    "website": "szabist.edu.pk",
    "deadline": "2026-08-18"
  },
  {
    "name": "Sir Syed University",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "Engineering, CS, Business",
    "min_merit": 60,
    "max_merit": 85,
    "fee_per_year": 120000,
    "hostel": "Yes",
    "hec_rank": 18,
    "website": "ssuet.edu.pk",
    "deadline": "2026-09-08"
  },
  {
    "name": "DOW University of Health Sciences",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "Medicine, Dentistry, Pharmacy, Nursing",
    "min_merit": 82,
    "max_merit": 97,
    "fee_per_year": 55000,
    "hostel": "Yes",
    "hec_rank": 19,
    "website": "duhs.edu.pk",
    "deadline": "2026-07-28"
  },
  {
    "name": "Habib University",
    "city": "Karachi",
    "province": "Sindh",
    "programs": "CS, Engineering, Social Sciences, Liberal Arts",
    "min_merit": 74,
    "max_merit": 94,
    "fee_per_year": 600000,
    "hostel": "Yes",
    "hec_rank": 20,
    "website": "habib.edu.pk",
    "deadline": "2026-08-05"
  },
  {
    "name": "Mehran University",
    "city": "Jamshoro",
    "province": "Sindh",
    "programs": "Engineering, CS, Architecture",
    "min_merit": 65,
    "max_merit": 88,
    "fee_per_year": 30000,
    "hostel": "Yes",
    "hec_rank": 17,
    "website": "muet.edu.pk",
    "deadline": "2026-09-20"
  },
  {
    "name": "University of Sindh",
    "city": "Jamshoro",
    "province": "Sindh",
    "programs": "Arts, Science, Law, Commerce, IT",
    "min_merit": 52,
    "max_merit": 80,
    "fee_per_year": 18000,
    "hostel": "Yes",
    "hec_rank": 30,
    "website": "usindh.edu.pk",
    "deadline": "2026-09-25"
  },
  {
    "name": "Liaquat Univ of Medical Sciences",
    "city": "Jamshoro",
    "province": "Sindh",
    "programs": "Medicine, Dentistry, Nursing",
    "min_merit": 80,
    "max_merit": 96,
    "fee_per_year": 40000,
    "hostel": "Yes",
    "hec_rank": 26,
    "website": "lumhs.edu.pk",
    "deadline": "2026-07-22"
  },
  {
    "name": "Sukkur IBA University",
    "city": "Sukkur",
    "province": "Sindh",
    "programs": "CS, Business, Education, Engineering",
    "min_merit": 66,
    "max_merit": 89,
    "fee_per_year": 90000,
    "hostel": "Yes",
    "hec_rank": 16,
    "website": "iba-suk.edu.pk",
    "deadline": "2026-08-12"
  },
  {
    "name": "Shah Abdul Latif University",
    "city": "Khairpur",
    "province": "Sindh",
    "programs": "Arts, Science, IT, Commerce",
    "min_merit": 50,
    "max_merit": 78,
    "fee_per_year": 16000,
    "hostel": "Yes",
    "hec_rank": 38,
    "website": "salu.edu.pk",
    "deadline": "2026-09-18"
  },
  {
    "name": "QUEST Nawabshah",
    "city": "Nawabshah",
    "province": "Sindh",
    "programs": "Engineering, CS, Architecture",
    "min_merit": 58,
    "max_merit": 84,
    "fee_per_year": 28000,
    "hostel": "Yes",
    "hec_rank": 33,
    "website": "quest.edu.pk",
    "deadline": "2026-09-12"
  },
  {
    "name": "FAST NUCES",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "CS, AI, SE",
    "min_merit": 78,
    "max_merit": 96,
    "fee_per_year": 185000,
    "hostel": "Yes",
    "hec_rank": 1,
    "website": "nu.edu.pk",
    "deadline": "2026-08-20"
  },
  {
    "name": "UET Lahore",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "Engineering, CS",
    "min_merit": 75,
    "max_merit": 94,
    "fee_per_year": 60000,
    "hostel": "Yes",
    "hec_rank": 3,
    "website": "uet.edu.pk",
    "deadline": "2026-08-10"
  },
  {
    "name": "LUMS",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "Business, CS, Law, Economics",
    "min_merit": 78,
    "max_merit": 97,
    "fee_per_year": 650000,
    "hostel": "Yes",
    "hec_rank": 5,
    "website": "lums.edu.pk",
    "deadline": "2026-08-01"
  },
  {
    "name": "UCP Lahore",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "CS, Business, Engineering",
    "min_merit": 60,
    "max_merit": 85,
    "fee_per_year": 150000,
    "hostel": "Yes",
    "hec_rank": 12,
    "website": "ucp.edu.pk",
    "deadline": "2026-09-01"
  },
  {
    "name": "Punjab University",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "Arts, Science, Law, Engineering, IT",
    "min_merit": 55,
    "max_merit": 85,
    "fee_per_year": 20000,
    "hostel": "Yes",
    "hec_rank": 11,
    "website": "pu.edu.pk",
    "deadline": "2026-09-05"
  },
  {
    "name": "GC University Lahore",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "Science, Arts, Business, IT",
    "min_merit": 62,
    "max_merit": 87,
    "fee_per_year": 35000,
    "hostel": "Yes",
    "hec_rank": 21,
    "website": "gcu.edu.pk",
    "deadline": "2026-08-28"
  },
  {
    "name": "University of Lahore",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "CS, Engineering, Medicine, Business",
    "min_merit": 58,
    "max_merit": 84,
    "fee_per_year": 165000,
    "hostel": "Yes",
    "hec_rank": 22,
    "website": "uol.edu.pk",
    "deadline": "2026-09-03"
  },
  {
    "name": "UMT Lahore",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "CS, Business, Engineering, Law",
    "min_merit": 59,
    "max_merit": 84,
    "fee_per_year": 160000,
    "hostel": "Yes",
    "hec_rank": 24,
    "website": "umt.edu.pk",
    "deadline": "2026-09-06"
  },
  {
    "name": "King Edward Medical University",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "Medicine, Dentistry",
    "min_merit": 88,
    "max_merit": 99,
    "fee_per_year": 65000,
    "hostel": "Yes",
    "hec_rank": 14,
    "website": "kemu.edu.pk",
    "deadline": "2026-07-18"
  },
  {
    "name": "FC College (FCCU)",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "CS, Business, Sciences, Humanities",
    "min_merit": 64,
    "max_merit": 88,
    "fee_per_year": 220000,
    "hostel": "Yes",
    "hec_rank": 23,
    "website": "fccollege.edu.pk",
    "deadline": "2026-08-26"
  },
  {
    "name": "UVAS Lahore",
    "city": "Lahore",
    "province": "Punjab",
    "programs": "Veterinary, Animal Sciences, Biotech",
    "min_merit": 60,
    "max_merit": 85,
    "fee_per_year": 45000,
    "hostel": "Yes",
    "hec_rank": 27,
    "website": "uvas.edu.pk",
    "deadline": "2026-08-24"
  },
  {
    "name": "UET Taxila",
    "city": "Taxila",
    "province": "Punjab",
    "programs": "Engineering, CS",
    "min_merit": 68,
    "max_merit": 90,
    "fee_per_year": 55000,
    "hostel": "Yes",
    "hec_rank": 15,
    "website": "uettaxila.edu.pk",
    "deadline": "2026-08-14"
  },
  {
    "name": "University of Faisalabad (UAF)",
    "city": "Faisalabad",
    "province": "Punjab",
    "programs": "Agriculture, Science, Vet, Engineering",
    "min_merit": 58,
    "max_merit": 85,
    "fee_per_year": 40000,
    "hostel": "Yes",
    "hec_rank": 25,
    "website": "uaf.edu.pk",
    "deadline": "2026-08-29"
  },
  {
    "name": "GC University Faisalabad",
    "city": "Faisalabad",
    "province": "Punjab",
    "programs": "Science, Arts, IT, Business",
    "min_merit": 56,
    "max_merit": 83,
    "fee_per_year": 30000,
    "hostel": "Yes",
    "hec_rank": 34,
    "website": "gcuf.edu.pk",
    "deadline": "2026-09-09"
  },
  {
    "name": "NTU Faisalabad",
    "city": "Faisalabad",
    "province": "Punjab",
    "programs": "Textile, Engineering, CS, Design",
    "min_merit": 60,
    "max_merit": 85,
    "fee_per_year": 80000,
    "hostel": "Yes",
    "hec_rank": 29,
    "website": "ntu.edu.pk",
    "deadline": "2026-08-21"
  },
  {
    "name": "Bahauddin Zakariya University",
    "city": "Multan",
    "province": "Punjab",
    "programs": "Engineering, Arts, Science, Pharmacy",
    "min_merit": 55,
    "max_merit": 83,
    "fee_per_year": 28000,
    "hostel": "Yes",
    "hec_rank": 28,
    "website": "bzu.edu.pk",
    "deadline": "2026-09-14"
  },
  {
    "name": "MNS UET Multan",
    "city": "Multan",
    "province": "Punjab",
    "programs": "Engineering, CS",
    "min_merit": 60,
    "max_merit": 86,
    "fee_per_year": 50000,
    "hostel": "Yes",
    "hec_rank": 31,
    "website": "mnsuet.edu.pk",
    "deadline": "2026-08-19"
  },
  {
    "name": "Islamia University Bahawalpur",
    "city": "Bahawalpur",
    "province": "Punjab",
    "programs": "Arts, Science, Engineering, IT, Pharmacy",
    "min_merit": 53,
    "max_merit": 82,
    "fee_per_year": 25000,
    "hostel": "Yes",
    "hec_rank": 32,
    "website": "iub.edu.pk",
    "deadline": "2026-09-16"
  },
  {
    "name": "University of Gujrat",
    "city": "Gujrat",
    "province": "Punjab",
    "programs": "CS, Business, Engineering, Arts",
    "min_merit": 54,
    "max_merit": 82,
    "fee_per_year": 38000,
    "hostel": "Yes",
    "hec_rank": 36,
    "website": "uog.edu.pk",
    "deadline": "2026-09-11"
  },
  {
    "name": "University of Sargodha",
    "city": "Sargodha",
    "province": "Punjab",
    "programs": "Science, Arts, Business, IT",
    "min_merit": 53,
    "max_merit": 81,
    "fee_per_year": 26000,
    "hostel": "Yes",
    "hec_rank": 37,
    "website": "su.edu.pk",
    "deadline": "2026-09-13"
  },
  {
    "name": "UET Lahore (RCET Gujranwala)",
    "city": "Gujranwala",
    "province": "Punjab",
    "programs": "Engineering, CS",
    "min_merit": 62,
    "max_merit": 86,
    "fee_per_year": 52000,
    "hostel": "Yes",
    "hec_rank": 35,
    "website": "uet.edu.pk",
    "deadline": "2026-08-16"
  },
  {
    "name": "University of Sialkot",
    "city": "Sialkot",
    "province": "Punjab",
    "programs": "CS, Business, Engineering",
    "min_merit": 52,
    "max_merit": 80,
    "fee_per_year": 95000,
    "hostel": "Yes",
    "hec_rank": 40,
    "website": "uskt.edu.pk",
    "deadline": "2026-09-22"
  },
  {
    "name": "Wah Engineering College",
    "city": "Wah Cantt",
    "province": "Punjab",
    "programs": "Engineering, CS",
    "min_merit": 58,
    "max_merit": 84,
    "fee_per_year": 60000,
    "hostel": "Yes",
    "hec_rank": 39,
    "website": "wecuw.edu.pk",
    "deadline": "2026-08-27"
  },
  {
    "name": "PIEAS",
    "city": "Islamabad",
    "province": "Punjab",
    "programs": "Engineering, Physics, CS, Nuclear",
    "min_merit": 82,
    "max_merit": 98,
    "fee_per_year": 40000,
    "hostel": "Yes",
    "hec_rank": 2,
    "website": "pieas.edu.pk",
    "deadline": "2026-07-26"
  },
  {
    "name": "NUST",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "Engineering, CS, AI, Business",
    "min_merit": 80,
    "max_merit": 98,
    "fee_per_year": 200000,
    "hostel": "Yes",
    "hec_rank": 2,
    "website": "nust.edu.pk",
    "deadline": "2026-07-25"
  },
  {
    "name": "COMSATS",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "CS, Engineering, Biology",
    "min_merit": 65,
    "max_merit": 88,
    "fee_per_year": 120000,
    "hostel": "Yes",
    "hec_rank": 8,
    "website": "comsats.edu.pk",
    "deadline": "2026-08-25"
  },
  {
    "name": "Quaid-i-Azam University",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "Social Sciences, Chemistry, Physics, Biology",
    "min_merit": 65,
    "max_merit": 88,
    "fee_per_year": 25000,
    "hostel": "Yes",
    "hec_rank": 7,
    "website": "qau.edu.pk",
    "deadline": "2026-08-05"
  },
  {
    "name": "Air University",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "CS, Engineering, Business, Aviation",
    "min_merit": 65,
    "max_merit": 88,
    "fee_per_year": 120000,
    "hostel": "Yes",
    "hec_rank": 14,
    "website": "au.edu.pk",
    "deadline": "2026-08-22"
  },
  {
    "name": "FAST NUCES",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "CS, AI, SE, EE",
    "min_merit": 76,
    "max_merit": 95,
    "fee_per_year": 185000,
    "hostel": "Yes",
    "hec_rank": 1,
    "website": "nu.edu.pk",
    "deadline": "2026-08-17"
  },
  {
    "name": "International Islamic University",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "CS, Engineering, Law, Islamic Studies",
    "min_merit": 58,
    "max_merit": 84,
    "fee_per_year": 55000,
    "hostel": "Yes",
    "hec_rank": 26,
    "website": "iiu.edu.pk",
    "deadline": "2026-09-02"
  },
  {
    "name": "Bahria University",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "CS, Engineering, Business, Psychology",
    "min_merit": 63,
    "max_merit": 87,
    "fee_per_year": 145000,
    "hostel": "Yes",
    "hec_rank": 10,
    "website": "bahria.edu.pk",
    "deadline": "2026-08-31"
  },
  {
    "name": "Riphah International University",
    "city": "Rawalpindi",
    "province": "Federal",
    "programs": "Medicine, CS, Engineering, Business",
    "min_merit": 60,
    "max_merit": 86,
    "fee_per_year": 160000,
    "hostel": "Yes",
    "hec_rank": 27,
    "website": "riphah.edu.pk",
    "deadline": "2026-09-04"
  },
  {
    "name": "Arid Agriculture University",
    "city": "Rawalpindi",
    "province": "Federal",
    "programs": "Agriculture, CS, Business, Vet",
    "min_merit": 55,
    "max_merit": 82,
    "fee_per_year": 35000,
    "hostel": "Yes",
    "hec_rank": 30,
    "website": "uaar.edu.pk",
    "deadline": "2026-09-07"
  },
  {
    "name": "NUML Islamabad",
    "city": "Islamabad",
    "province": "Federal",
    "programs": "Languages, CS, Business, IR",
    "min_merit": 57,
    "max_merit": 83,
    "fee_per_year": 70000,
    "hostel": "Yes",
    "hec_rank": 28,
    "website": "numl.edu.pk",
    "deadline": "2026-08-23"
  },
  {
    "name": "GIK Institute",
    "city": "Topi",
    "province": "KPK",
    "programs": "Engineering, CS",
    "min_merit": 75,
    "max_merit": 94,
    "fee_per_year": 200000,
    "hostel": "Yes",
    "hec_rank": 5,
    "website": "giki.edu.pk",
    "deadline": "2026-08-12"
  },
  {
    "name": "UET Peshawar",
    "city": "Peshawar",
    "province": "KPK",
    "programs": "Engineering, CS, Architecture",
    "min_merit": 66,
    "max_merit": 89,
    "fee_per_year": 42000,
    "hostel": "Yes",
    "hec_rank": 13,
    "website": "uetpeshawar.edu.pk",
    "deadline": "2026-08-11"
  },
  {
    "name": "University of Peshawar",
    "city": "Peshawar",
    "province": "KPK",
    "programs": "Arts, Science, Law, Pharmacy",
    "min_merit": 54,
    "max_merit": 82,
    "fee_per_year": 22000,
    "hostel": "Yes",
    "hec_rank": 24,
    "website": "uop.edu.pk",
    "deadline": "2026-09-17"
  },
  {
    "name": "Khyber Medical University",
    "city": "Peshawar",
    "province": "KPK",
    "programs": "Medicine, Dentistry, Allied Health",
    "min_merit": 83,
    "max_merit": 97,
    "fee_per_year": 60000,
    "hostel": "Yes",
    "hec_rank": 22,
    "website": "kmu.edu.pk",
    "deadline": "2026-07-24"
  },
  {
    "name": "CECOS University",
    "city": "Peshawar",
    "province": "KPK",
    "programs": "Engineering, CS, Management",
    "min_merit": 56,
    "max_merit": 83,
    "fee_per_year": 110000,
    "hostel": "Yes",
    "hec_rank": 41,
    "website": "cecos.edu.pk",
    "deadline": "2026-09-19"
  },
  {
    "name": "COMSATS Abbottabad",
    "city": "Abbottabad",
    "province": "KPK",
    "programs": "CS, Engineering, Biosciences",
    "min_merit": 62,
    "max_merit": 86,
    "fee_per_year": 115000,
    "hostel": "Yes",
    "hec_rank": 18,
    "website": "cuiatd.edu.pk",
    "deadline": "2026-08-25"
  },
  {
    "name": "Abdul Wali Khan University",
    "city": "Mardan",
    "province": "KPK",
    "programs": "Science, Arts, CS, Business",
    "min_merit": 52,
    "max_merit": 80,
    "fee_per_year": 24000,
    "hostel": "Yes",
    "hec_rank": 42,
    "website": "awkum.edu.pk",
    "deadline": "2026-09-21"
  },
  {
    "name": "University of Balochistan",
    "city": "Quetta",
    "province": "Balochistan",
    "programs": "Arts, Science, Law, IT",
    "min_merit": 50,
    "max_merit": 78,
    "fee_per_year": 20000,
    "hostel": "Yes",
    "hec_rank": 43,
    "website": "uob.edu.pk",
    "deadline": "2026-09-24"
  },
  {
    "name": "BUITEMS",
    "city": "Quetta",
    "province": "Balochistan",
    "programs": "Engineering, CS, Management, ICT",
    "min_merit": 55,
    "max_merit": 82,
    "fee_per_year": 45000,
    "hostel": "Yes",
    "hec_rank": 34,
    "website": "buitems.edu.pk",
    "deadline": "2026-08-22"
  },
  {
    "name": "Mirpur Univ of Sci & Tech (MUST)",
    "city": "Mirpur",
    "province": "AJK",
    "programs": "Engineering, CS, Business",
    "min_merit": 56,
    "max_merit": 83,
    "fee_per_year": 40000,
    "hostel": "Yes",
    "hec_rank": 44,
    "website": "must.edu.pk",
    "deadline": "2026-09-15"
  },
  {
    "name": "Karakoram International University",
    "city": "Gilgit",
    "province": "GB",
    "programs": "Science, Arts, CS, Business",
    "min_merit": 50,
    "max_merit": 78,
    "fee_per_year": 30000,
    "hostel": "Yes",
    "hec_rank": 45,
    "website": "kiu.edu.pk",
    "deadline": "2026-09-23"
  }
];
